insert into speciality (sp_name) values 
('Allergy And Immunology'),
('Allergy Specialist'),
('Andrology And Male Fertility'),
('Applied Psychologist'),
('Audiologist'),
('Audiometrist'),
('Ayurvedic'),
('Ayurvedic and Alternative Medicine'),
('Ayurvedic Physician (Boils and Wounds Special)'),
('Back Pain Treatment'),
('Back Pain Treatment And Sports Medicine'),
('Behaviour Therapist'),
('Breast Feeding'),
('Cardiac Electrophysiologist'),
('Cardiologist'),
('Cardiologist And Cardiac Electrophysiologist'),
('Cardiothoracic Surgeon'),
('Chest Physician'),
('Chest Specialist'),
('Child and Adolescent Phychiatrist'),
('Child Psychiatrist'),
('Chiropractor'),
('Clinical Haematologist'),
('Clinical Hypnotist'),
('Clinical Microbiology / Immunology'),
('Clinical Oncologist'),
('Clinical Psychologist'),
('Co-Ordinating Dr (Sleep Medicine)'),
('Consultant Dental Surgeon And Prosthodontist'),
('Consultant Dental Surgeon And Restorative Dentistry'),
('Consultant Judicial Medicine'),
('Cosmetic Dermatology'),
('Cosmetic Oculoplasty'),
('Counseling Psychologist'),
('Counselling'),
('Counsellor'),
('Dental And Maxillo-Facial Surgeon'),
('Dental And Maxillofacial Surgeon'),
('Dental Surgeon'),
('Dental Surgeon (Preventive Dentistry)'),
('Dental Surgeon / Restorative Dentistry'),
('Dental Surgeon ¿ General And Laser'),
('Dermatologist'),
('Dermatologist And Hair Clinic'),
('Diabetic Care'),
('Diabetic Educator'),
('Diabetic Specialist'),
('Dietician'),
('Dietician and Nutrician'),
('Eeg'),
('Embryologist'),
('Endocrinologist'),
('Endocrinologist/Diabetologist'),
('Ent Surgeon'),
('Eye Surgeon'),
('Facial Surgeon'),
('Family /General Counceller'),
('Family Physician'),
('Fertility Counselor / Clinical Embryologist'),
('Gastroenterological Surgeon'),
('Gastroenterologist'),
('Gastroenterologist And Hepatologist'),
('Gastroenterologist Surgeon'),
('Gastrointestinal Surgeon'),
('General Disorders'),
('General Physician'),
('General Practitioner'),
('Geneticist'),
('Genito Urinary Surgeon'),
('Gynaecological Cancer Surgeon'),
('Gynaecologist'),
('Gynaecologist And Consultant In Fertility'),
('Gynaecologist And Obstrician'),
('Gynaecologist And Specialist In Sub-Fertility'),
('Gynaecologist,Fertility,Reproductive,Endocrinologist'),
('Haemato Oncologist'),
('Haematologist'),
('Hair Transplant'),
('Health Management Program'),
('Hepatobiliary Surgeon'),
('Immunologist'),
('Infertility Physician And Clinical Embryologist'),
('Internal Medicine and Gastroenterology'),
('Interventional Radiologist'),
('Kidney Transplant Surgeon'),
('Lanka Hospital'),
('Laparoscopic and Bariatric Surgeon'),
('Laparoscopy And Colorectal Surgeon'),
('Liver Centre'),
('Male Fertility'),
('Medical And Clinical Geneticist'),
('Medical Examination(Visa)'),
('Medical Gastroenterologist'),
('Medical Microbiologist'),
('Medical Nutritionist'),
('Medical Officer'),
('Medical Officer Well Woman Clinics'),
('Memory Clinic'),
('Microbiologist'),
('Mycologist'),
('Mycologist / Microbiologist'),
('Neonatal Paediatrician'),
('Neonatologist'),
('Nephrologist'),
('Nephrologist And Genaral Physician'),
('Neuro Physician'),
('Neuro Physiologist'),
('Neuro Surgeon'),
('Neurologist'),
('Nutritionist'),
('Obstetrician And Fetal Medicine Specialist'),
('Obstetrician And Gynaecologist'),
('Occupational Therapist'),
('Oculoplastic Surgeon'),
('Onco Surgeon'),
('Oncological Surgeon'),
('Oncological Surgeon - Surgeon'),
('Oncologist'),
('Oncologist - Cancer Specialist'),
('Ophthalmologist'),
('Oral and Maxillofacial Surgeon'),
('Orthodontist'),
('Orthopaedic Surgeon'),
('Paediatric Cardiologist'),
('Paediatric Cardiothoracic Surgeon'),
('Paediatric Consultant Radiologist'),
('Paediatric Dermatologist'),
('Paediatric Dermatologist And Dermatolog'),
('Paediatric Endocrinologist And Diabetologist'),
('Paediatric Interventional Cardiologist'),
('Paediatric Neonatologist'),
('Paediatric Nephrologist'),
('Paediatric Neurologist'),
('Paediatric Ophthalmologist'),
('Paediatric Orthopaedic Surgeon'),
('Paediatric Psychiatrist'),
('Paediatric Surgeon'),
('Paediatrician'),
('Paediatrician And Neonatal Paediatrician'),
('Paediatrics And Neonatology'),
('Paediatrics And Paediatric Neonatology'),
('Paediatrics And Paediatric Neuro Disability'),
('Pain Management'),
('Parasitologist'),
('Pathologist'),
('Pediatric Cardiac Surgeon'),
('Physician'),
('Physician and Endocrinologists/Diabetologist'),
('Physician and Endocrinologist'),
('Physician / Family Medicine'),
('Physician And Gastro Enterologists'),
('Physician And Immunologist'),
('Physiotherapist'),
('Plastic And Reconstructive Surgeon'),
('Plastic Surgeon'),
('Psychiatrist'),
('Psychiatrist (Child And Adolescents)'),
('Psycho Social Practitioner'),
('Psychological Counseller'),
('Psychological Counselling'),
('Psychologist'),
('Psychotherapist/Clinical Psychologist'),
('Radiologists'),
('Respiratory And Chest Physician'),
('Restorative Dentist'),
('Restorative Dentistry'),
('Rheumatologist'),
('Rheumatologist And General Disorders'),
('Rheumatology And Rehabilitation'),
('S.T.D'),
('Scanning'),
('Sexual Health'),
('Sexual Medicine'),
('Sexual Medicine And Sexual Health'),
('Shape Up Clinic'),
('Skin Care and Cosmetic Centre - Plastic Surgeon'),
('Skin Care And Cosmetic Consultant Dermatologist'),
('Skin Care And Cosmetic Oculoplastic Surgeon'),
('Speech And Language Therapist'),
('Speech Language Pathalogist And Audiologist'),
('Speech Pathologist/Therapist'),
('Speech Therapist'),
('Speech Therapist And Audiologist'),
('Sports Medicine'),
('Sports Medicine And Sports Psychology'),
('Surgeon'),
('Thoracic Surgeon'),
('Transfusion Physician'),
('Transplant And Genito Urinary Surgeon'),
('Urinary Disorders And General Disorders'),
('Urological Surgeon'),
('Urologist'),
('Urologist And Transplant Surgeon'),
('Vaccinologist'),
('Vaccinologist And Medical Virologist'),
('Vascular And Transplant Surgeon'),
('Vascular Surgeon'),
('Venereologist'),
('Vip Serene Centre - Nawaloka Only'),
('Virologist'),
('Wellness And Weight Management');