contactinfo_index:
    path:     /
    defaults: { _controller: "AppBundle:ContactInfo:index" }
    methods:  GET

contactinfo_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:ContactInfo:show" }
    methods:  GET

contactinfo_new:
    path:     /new
    defaults: { _controller: "AppBundle:ContactInfo:new" }
    methods:  [GET, POST]

contactinfo_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:ContactInfo:edit" }
    methods:  [GET, POST]

contactinfo_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:ContactInfo:delete" }
    methods:  DELETE

contactinfo_dropdown:
    path:     /dropdown
    defaults: { _controller: "AppBundle:ContactInfo:dropdown" }
    #methods:  DELETE  

contactinfo_saveDataContactInfo:
    path:   /savaDataContactInfo
    defaults: { _controller: "AppBundle:ContactInfo:saveDataContactInfo" }      
