medicaldetail_index:
    path:     /
    defaults: { _controller: "AppBundle:MedicalDetail:index" }
    methods:  GET

medicaldetail_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:MedicalDetail:show" }
    methods:  GET

medicaldetail_new:
    path:     /new
    defaults: { _controller: "AppBundle:MedicalDetail:new" }
    methods:  [GET, POST]

medicaldetail_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:MedicalDetail:edit" }
    methods:  [GET, POST]

medicaldetail_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:MedicalDetail:delete" }
    methods:  DELETE
