pricing_index:
    path:     /
    defaults: { _controller: "AppBundle:Pricing:index" }
    methods:  GET

pricing_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Pricing:show" }
    methods:  GET

pricing_new:
    path:     /new
    defaults: { _controller: "AppBundle:Pricing:new" }
    methods:  [GET, POST]

pricing_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Pricing:edit" }
    methods:  [GET, POST]

pricing_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Pricing:delete" }
    methods:  DELETE
