socialnetwork_index:
    path:     /
    defaults: { _controller: "AppBundle:SocialNetwork:index" }
    methods:  GET

socialnetwork_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:SocialNetwork:show" }
    methods:  GET

socialnetwork_new:
    path:     /new
    defaults: { _controller: "AppBundle:SocialNetwork:new" }
    methods:  [GET, POST]

socialnetwork_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:SocialNetwork:edit" }
    methods:  [GET, POST]

socialnetwork_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:SocialNetwork:delete" }
    methods:  DELETE
