speciality_index:
    path:     /
    defaults: { _controller: "AppBundle:Speciality:index" }
    methods:  GET

speciality_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Speciality:show" }
    methods:  GET

speciality_new:
    path:     /new
    defaults: { _controller: "AppBundle:Speciality:new" }
    methods:  [GET, POST]

speciality_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Speciality:edit" }
    methods:  [GET, POST]

speciality_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Speciality:delete" }
    methods:  DELETE
