AppBundle\Entity\Category:
    type: entity
    table: category
    id:
        catId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: cat_id
            generator:
                strategy: IDENTITY
    fields:
        catName:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: cat_name
        catActive:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: cat_active
    lifecycleCallbacks: {  }
