AppBundle\Entity\Speciality:
    type: entity
    table: speciality
    indexes:
        fk_specialities_user1_idx:
            columns:
                - usr_id
    id:
        spId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: sp_id
            generator:
                strategy: IDENTITY
    fields:
        spName:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: sp_name
        spCreated:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
            column: sp_created
        spActive:
            type: boolean
            nullable: true
            options:
                default: '1'
            column: sp_active
    manyToOne:
        usr:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usr_id:
                    referencedColumnName: usr_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
