AppBundle\Entity\State:
    type: entity
    table: state
    indexes:
        FK_state_country:
            columns:
                - cou_id
    id:
        staId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: sta_id
            generator:
                strategy: IDENTITY
    fields:
        staName:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: sta_name
        staActive:
            type: boolean
            nullable: true
            options:
                default: '1'
            column: sta_active
        staCode:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: sta_code
    manyToOne:
        cou:
            targetEntity: Country
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cou_id:
                    referencedColumnName: cou_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
