AppBundle\Entity\States:
    type: entity
    table: states
    id:
        stateCode:
            type: string
            nullable: false
            length: 2
            options:
                fixed: true
            id: true
            column: state_code
            generator:
                strategy: IDENTITY
    fields:
        state:
            type: string
            nullable: false
            length: 22
            options:
                fixed: false
        lat:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        lng:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
