AppBundle\Entity\UserResetPassword:
    type: entity
    table: user_reset_password
    indexes:
        FK_user_set_password_user:
            columns:
                - usr_id
    id:
        uspId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: usp_id
            generator:
                strategy: IDENTITY
    fields:
        uspToken:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
            column: usp_token
        uspNewPassword:
            type: string
            nullable: false
            length: 75
            options:
                fixed: false
            column: usp_new_password
        uspCreated:
            type: date
            nullable: true
            column: usp_created
        uspActive:
            type: boolean
            nullable: true
            options:
                default: '1'
            column: usp_active
    manyToOne:
        usr:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usr_id:
                    referencedColumnName: usr_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
