AppBundle\Entity\UserHasSpeciality:
    type: entity
    table: user_has_speciality
    indexes:
        FK_user_has_specialitie_speciality:
            columns:
                - sp_id
        FK_user_has_specialitie_user:
            columns:
                - usr_id
    id:
        uhsId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: uhs_id
            generator:
                strategy: IDENTITY
    manyToOne:
        sp:
            targetEntity: Speciality
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sp_id:
                    referencedColumnName: sp_id
            orphanRemoval: false
        usr:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usr_id:
                    referencedColumnName: usr_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
