web_homepage:
    path:     /
    defaults: { _controller: WebBundle:Default:index }

web_get_cities:
  path:     /getCitiesByState
  defaults: { _controller: "WebBundle:Default:getCitiesByState" }
  methods:  POST

web_show_profile:
  path:     /showProfile/{id}
  defaults: { _controller: "WebBundle:Default:showProfile" }
  methods:  GET

web_landing:
  path:     /landing
  defaults: { _controller: "WebBundle:Default:landing" }
  methods:  GET


