web_homepage:
    path:     /
    defaults: { _controller: WebBundle:Default:index }

web_get_cities:
  path:     /getCitiesByState
  defaults: { _controller: "WebBundle:Default:getCitiesByState" }
  methods:  POST

web_show_profile:
  path:     /show/profile
  defaults: { _controller: "WebBundle:Default:showFullProfile" }

